///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest23
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest23Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("24380eb5-eb83-4abe-8a60-36d81d3e3ef1")]
    public partial class MyTest23Repository : RepoGenBaseFolder
    {
        static MyTest23Repository instance = new MyTest23Repository();
        MyTest23RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyTest23RepositoryFolders.RebuildingMysqlRemovingDataSavedToAppFolder _rebuildingmysqlremovingdatasavedto;
        MyTest23RepositoryFolders.MeedomComJorgenMeedomdkPhpGoogleCAppFolder _meedomcomjorgenmeedomdkphpgooglec;
        MyTest23RepositoryFolders.MeedomComJorgenMeedomdkPhpAppFolder _meedomcomjorgenmeedomdkphp;
        MyTest23RepositoryFolders.WordPressInstallationAppFolder _wordpressinstallation;
        MyTest23RepositoryFolders.NyFaneGoogleChromeAppFolder _nyfanegooglechrome;
        MyTest23RepositoryFolders.NyFaneAppFolder _nyfane;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest23Repository element repository.
        /// </summary>
        [RepositoryFolder("24380eb5-eb83-4abe-8a60-36d81d3e3ef1")]
        public static MyTest23Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest23Repository() 
            : base("MyTest23Repository", "/", null, 0, false, "24380eb5-eb83-4abe-8a60-36d81d3e3ef1", ".\\RepositoryImages\\MyTest23Repository24380eb5.rximgres")
        {
            _applicationundertest = new MyTest23RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _rebuildingmysqlremovingdatasavedto = new MyTest23RepositoryFolders.RebuildingMysqlRemovingDataSavedToAppFolder(this);
            _meedomcomjorgenmeedomdkphpgooglec = new MyTest23RepositoryFolders.MeedomComJorgenMeedomdkPhpGoogleCAppFolder(this);
            _meedomcomjorgenmeedomdkphp = new MyTest23RepositoryFolders.MeedomComJorgenMeedomdkPhpAppFolder(this);
            _wordpressinstallation = new MyTest23RepositoryFolders.WordPressInstallationAppFolder(this);
            _nyfanegooglechrome = new MyTest23RepositoryFolders.NyFaneGoogleChromeAppFolder(this);
            _nyfane = new MyTest23RepositoryFolders.NyFaneAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("24380eb5-eb83-4abe-8a60-36d81d3e3ef1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("136ddaac-114f-4a54-9ff5-2a8b314bcd83")]
        public virtual MyTest23RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The RebuildingMysqlRemovingDataSavedTo folder.
        /// </summary>
        [RepositoryFolder("fa3d79e0-8110-474e-a705-63981eb8f1fa")]
        public virtual MyTest23RepositoryFolders.RebuildingMysqlRemovingDataSavedToAppFolder RebuildingMysqlRemovingDataSavedTo
        {
            get { return _rebuildingmysqlremovingdatasavedto; }
        }

        /// <summary>
        /// The MeedomComJorgenMeedomdkPhpGoogleC folder.
        /// </summary>
        [RepositoryFolder("deef4d75-51cd-4841-bfe2-1028f21f7ee1")]
        public virtual MyTest23RepositoryFolders.MeedomComJorgenMeedomdkPhpGoogleCAppFolder MeedomComJorgenMeedomdkPhpGoogleC
        {
            get { return _meedomcomjorgenmeedomdkphpgooglec; }
        }

        /// <summary>
        /// The MeedomComJorgenMeedomdkPhp folder.
        /// </summary>
        [RepositoryFolder("e58a3542-f442-4cca-a049-971017e0f4cf")]
        public virtual MyTest23RepositoryFolders.MeedomComJorgenMeedomdkPhpAppFolder MeedomComJorgenMeedomdkPhp
        {
            get { return _meedomcomjorgenmeedomdkphp; }
        }

        /// <summary>
        /// The WordPressInstallation folder.
        /// </summary>
        [RepositoryFolder("679402c5-a5bd-4d32-8999-c69b68ad2f07")]
        public virtual MyTest23RepositoryFolders.WordPressInstallationAppFolder WordPressInstallation
        {
            get { return _wordpressinstallation; }
        }

        /// <summary>
        /// The NyFaneGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("f7b1980f-ac83-405a-a951-18633b41c2fb")]
        public virtual MyTest23RepositoryFolders.NyFaneGoogleChromeAppFolder NyFaneGoogleChrome
        {
            get { return _nyfanegooglechrome; }
        }

        /// <summary>
        /// The NyFane folder.
        /// </summary>
        [RepositoryFolder("95a81178-cf32-44a5-9b71-6708677d5bb2")]
        public virtual MyTest23RepositoryFolders.NyFaneAppFolder NyFane
        {
            get { return _nyfane; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest23RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("136ddaac-114f-4a54-9ff5-2a8b314bcd83")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "136ddaac-114f-4a54-9ff5-2a8b314bcd83", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("136ddaac-114f-4a54-9ff5-2a8b314bcd83")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("136ddaac-114f-4a54-9ff5-2a8b314bcd83")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The RebuildingMysqlRemovingDataSavedToAppFolder folder.
        /// </summary>
        [RepositoryFolder("fa3d79e0-8110-474e-a705-63981eb8f1fa")]
        public partial class RebuildingMysqlRemovingDataSavedToAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _jscommentcontainertimelineitemInfo;

            /// <summary>
            /// Creates a new RebuildingMysqlRemovingDataSavedTo  folder.
            /// </summary>
            public RebuildingMysqlRemovingDataSavedToAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RebuildingMysqlRemovingDataSavedTo", "/dom[@domain='github.com']", parentFolder, 30000, null, false, "fa3d79e0-8110-474e-a705-63981eb8f1fa", "")
            {
                _jscommentcontainertimelineitemInfo = new RepoItemInfo(this, "JsCommentContainerTimelineItem", ".//div[#'discussion_bucket']/div[1]/div/div[1]/div[3]/div", 30000, null, "880230fa-f765-42c0-af14-29e60edb3111");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fa3d79e0-8110-474e-a705-63981eb8f1fa")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fa3d79e0-8110-474e-a705-63981eb8f1fa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The JsCommentContainerTimelineItem item.
            /// </summary>
            [RepositoryItem("880230fa-f765-42c0-af14-29e60edb3111")]
            public virtual Ranorex.DivTag JsCommentContainerTimelineItem
            {
                get
                {
                    return _jscommentcontainertimelineitemInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The JsCommentContainerTimelineItem item info.
            /// </summary>
            [RepositoryItemInfo("880230fa-f765-42c0-af14-29e60edb3111")]
            public virtual RepoItemInfo JsCommentContainerTimelineItemInfo
            {
                get
                {
                    return _jscommentcontainertimelineitemInfo;
                }
            }
        }

        /// <summary>
        /// The MeedomComJorgenMeedomdkPhpGoogleCAppFolder folder.
        /// </summary>
        [RepositoryFolder("deef4d75-51cd-4841-bfe2-1028f21f7ee1")]
        public partial class MeedomComJorgenMeedomdkPhpGoogleCAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _adresseogsogelinjeInfo;
            RepoItemInfo _pagetablistInfo;

            /// <summary>
            /// Creates a new MeedomComJorgenMeedomdkPhpGoogleC  folder.
            /// </summary>
            public MeedomComJorgenMeedomdkPhpGoogleCAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MeedomComJorgenMeedomdkPhpGoogleC", "/form[@title>'meedom.com/jorgen/meedomdk.php']", parentFolder, 30000, null, true, "deef4d75-51cd-4841-bfe2-1028f21f7ee1", "")
            {
                _adresseogsogelinjeInfo = new RepoItemInfo(this, "AdresseOgSogelinje", "container[@accessiblename>'meedom.com/jorgen/meedomdk.php']/container[@accessiblename='Google Chrome']/container[2]/container[1]/container[2]/container[1]/text[@accessiblename='Adresse og søgelinje']", 30000, null, "4b8a0dec-c2e6-43f6-b9e3-2f6e8e359a73");
                _pagetablistInfo = new RepoItemInfo(this, "PageTabList", "container[@accessiblename>'Rediger indlæg ‹ Meedom —']/container[@accessiblename='Google Chrome']//tabpagelist[@accessiblerole='PageTabList']", 30000, null, "6f066097-71e1-4a7d-93f6-778c0c27271d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("deef4d75-51cd-4841-bfe2-1028f21f7ee1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("deef4d75-51cd-4841-bfe2-1028f21f7ee1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AdresseOgSogelinje item.
            /// </summary>
            [RepositoryItem("4b8a0dec-c2e6-43f6-b9e3-2f6e8e359a73")]
            public virtual Ranorex.Text AdresseOgSogelinje
            {
                get
                {
                    return _adresseogsogelinjeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AdresseOgSogelinje item info.
            /// </summary>
            [RepositoryItemInfo("4b8a0dec-c2e6-43f6-b9e3-2f6e8e359a73")]
            public virtual RepoItemInfo AdresseOgSogelinjeInfo
            {
                get
                {
                    return _adresseogsogelinjeInfo;
                }
            }

            /// <summary>
            /// The PageTabList item.
            /// </summary>
            [RepositoryItem("6f066097-71e1-4a7d-93f6-778c0c27271d")]
            public virtual Ranorex.TabPageList PageTabList
            {
                get
                {
                    return _pagetablistInfo.CreateAdapter<Ranorex.TabPageList>(true);
                }
            }

            /// <summary>
            /// The PageTabList item info.
            /// </summary>
            [RepositoryItemInfo("6f066097-71e1-4a7d-93f6-778c0c27271d")]
            public virtual RepoItemInfo PageTabListInfo
            {
                get
                {
                    return _pagetablistInfo;
                }
            }
        }

        /// <summary>
        /// The MeedomComJorgenMeedomdkPhpAppFolder folder.
        /// </summary>
        [RepositoryFolder("e58a3542-f442-4cca-a049-971017e0f4cf")]
        public partial class MeedomComJorgenMeedomdkPhpAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new MeedomComJorgenMeedomdkPhp  folder.
            /// </summary>
            public MeedomComJorgenMeedomdkPhpAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MeedomComJorgenMeedomdkPhp", "/dom[@domain='meedom.com']", parentFolder, 30000, null, false, "e58a3542-f442-4cca-a049-971017e0f4cf", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e58a3542-f442-4cca-a049-971017e0f4cf")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e58a3542-f442-4cca-a049-971017e0f4cf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The WordPressInstallationAppFolder folder.
        /// </summary>
        [RepositoryFolder("679402c5-a5bd-4d32-8999-c69b68ad2f07")]
        public partial class WordPressInstallationAppFolder : RepoGenBaseFolder
        {
            MyTest23RepositoryFolders.EditPostLayoutFolder _editpostlayout;
            MyTest23RepositoryFolders.SetupFolder _setup;
            MyTest23RepositoryFolders.FormTableInstallSuccessFolder _formtableinstallsuccess;
            RepoItemInfo _dadkInfo;
            RepoItemInfo _languagecontinueInfo;
            RepoItemInfo _weblogtitleInfo;
            RepoItemInfo _userloginInfo;
            RepoItemInfo _adminemailInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _logindInfo;
            RepoItemInfo _wpsubmitInfo;
            RepoItemInfo _contentInfo;
            RepoItemInfo _savepostInfo;
            RepoItemInfo _insideInfo;
            RepoItemInfo _dengodehistorieovigssenestebogomInfo;
            RepoItemInfo _languageInfo;
            RepoItemInfo _titleInfo;
            RepoItemInfo _tilpasditwebstedInfo;
            RepoItemInfo _h3tagfarverInfo;
            RepoItemInfo _customInfo;
            RepoItemInfo _irisslideroffsetuicorneralluislidInfo;
            RepoItemInfo _saveInfo;

            /// <summary>
            /// Creates a new WordPressInstallation  folder.
            /// </summary>
            public WordPressInstallationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WordPressInstallation", "/dom[@domain='localhost']", parentFolder, 30000, null, false, "679402c5-a5bd-4d32-8999-c69b68ad2f07", "")
            {
                _editpostlayout = new MyTest23RepositoryFolders.EditPostLayoutFolder(this);
                _setup = new MyTest23RepositoryFolders.SetupFolder(this);
                _formtableinstallsuccess = new MyTest23RepositoryFolders.FormTableInstallSuccessFolder(this);
                _dadkInfo = new RepoItemInfo(this, "DaDK", ".//select[#'language']/option[@value='da_DK']", 30000, null, "383a1387-5da3-4bea-a002-63377e2f3cf3");
                _languagecontinueInfo = new RepoItemInfo(this, "LanguageContinue", ".//input[#'language-continue']", 30000, null, "767ce1fe-3559-4c48-b2b6-4a4fb3bc8e60");
                _weblogtitleInfo = new RepoItemInfo(this, "WeblogTitle", ".//input[#'weblog_title']", 30000, null, "9a7df755-9a30-47a2-a979-ba5868dab223");
                _userloginInfo = new RepoItemInfo(this, "UserLogin", ".//input[#'user_login']", 30000, null, "8d827f22-b01a-409a-b888-bfa0f2235398");
                _adminemailInfo = new RepoItemInfo(this, "AdminEmail", ".//input[#'admin_email']", 30000, null, "3dc86b10-8c57-4bd2-a1e3-f2fda9c6f598");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//input[#'submit']", 30000, null, "5817c855-6be6-4d08-a337-f278a062e4d0");
                _logindInfo = new RepoItemInfo(this, "LogInd", "body/p[3]/a[@innertext='Log ind']", 30000, null, "61d50a52-2471-4470-89f2-39bb33dfbada");
                _wpsubmitInfo = new RepoItemInfo(this, "WpSubmit", ".//input[#'wp-submit']", 30000, null, "5a302508-2866-49d1-afc5-bb182774c100");
                _contentInfo = new RepoItemInfo(this, "Content", ".//textarea[#'content']", 30000, null, "989b25fa-61bd-4568-a444-4929a399dcea");
                _savepostInfo = new RepoItemInfo(this, "SavePost", ".//input[#'save-post']", 30000, null, "f4b6474c-23b1-4923-88ce-dc420dbb7b2b");
                _insideInfo = new RepoItemInfo(this, "Inside", ".//div[#'dashboard_quick_press']/div", 30000, null, "718a3a78-2146-4a6e-91ca-a418aff259df");
                _dengodehistorieovigssenestebogomInfo = new RepoItemInfo(this, "DenGodeHistorieOvigsSenesteBogOm", ".//main[#'site-content']/article//p[@innertext>'Den gode historie. Øvigs seneste']", 30000, null, "0eaa612e-2fef-4cdb-b936-c7cc2d3b61c8");
                _languageInfo = new RepoItemInfo(this, "Language", ".//select[#'language']", 30000, null, "7706c093-9c04-4040-8f52-729d988bece9");
                _titleInfo = new RepoItemInfo(this, "Title", ".//input[#'title']", 30000, null, "cb8306c0-7bf5-4e6a-b8ad-dab2eb3847be");
                _tilpasditwebstedInfo = new RepoItemInfo(this, "TilpasDitWebsted", ".//div[#'welcome-panel']/div/div/div[1]/a[1]", 30000, null, "77f0374a-60f7-4b0a-9704-9eadbda64c06");
                _h3tagfarverInfo = new RepoItemInfo(this, "H3TagFarver", ".//li[#'accordion-section-colors']/h3[@innertext='Farver']", 30000, null, "188de965-b968-4361-b0e6-fc1a8bc64715");
                _customInfo = new RepoItemInfo(this, "Custom", ".//li[#'customize-control-accent_hue_active']/?/?/label[@innertext='Custom']", 30000, null, "71d2bbb0-2eeb-452d-88d8-588d07b566fe");
                _irisslideroffsetuicorneralluislidInfo = new RepoItemInfo(this, "IrisSliderOffsetUiCornerAllUiSlid", ".//li[#'customize-control-accent_hue']/div[2]/label/div/div/div[2]/div", 30000, null, "c3e89168-dca9-4733-8c12-54ef9a01ea1e");
                _saveInfo = new RepoItemInfo(this, "Save", ".//input[#'save']", 30000, null, "85ea9211-cab2-44eb-a802-0dbb45e6b9af");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("679402c5-a5bd-4d32-8999-c69b68ad2f07")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("679402c5-a5bd-4d32-8999-c69b68ad2f07")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DaDK item.
            /// </summary>
            [RepositoryItem("383a1387-5da3-4bea-a002-63377e2f3cf3")]
            public virtual Ranorex.OptionTag DaDK
            {
                get
                {
                    return _dadkInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The DaDK item info.
            /// </summary>
            [RepositoryItemInfo("383a1387-5da3-4bea-a002-63377e2f3cf3")]
            public virtual RepoItemInfo DaDKInfo
            {
                get
                {
                    return _dadkInfo;
                }
            }

            /// <summary>
            /// The LanguageContinue item.
            /// </summary>
            [RepositoryItem("767ce1fe-3559-4c48-b2b6-4a4fb3bc8e60")]
            public virtual Ranorex.InputTag LanguageContinue
            {
                get
                {
                    return _languagecontinueInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LanguageContinue item info.
            /// </summary>
            [RepositoryItemInfo("767ce1fe-3559-4c48-b2b6-4a4fb3bc8e60")]
            public virtual RepoItemInfo LanguageContinueInfo
            {
                get
                {
                    return _languagecontinueInfo;
                }
            }

            /// <summary>
            /// The WeblogTitle item.
            /// </summary>
            [RepositoryItem("9a7df755-9a30-47a2-a979-ba5868dab223")]
            public virtual Ranorex.InputTag WeblogTitle
            {
                get
                {
                    return _weblogtitleInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The WeblogTitle item info.
            /// </summary>
            [RepositoryItemInfo("9a7df755-9a30-47a2-a979-ba5868dab223")]
            public virtual RepoItemInfo WeblogTitleInfo
            {
                get
                {
                    return _weblogtitleInfo;
                }
            }

            /// <summary>
            /// The UserLogin item.
            /// </summary>
            [RepositoryItem("8d827f22-b01a-409a-b888-bfa0f2235398")]
            public virtual Ranorex.InputTag UserLogin
            {
                get
                {
                    return _userloginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserLogin item info.
            /// </summary>
            [RepositoryItemInfo("8d827f22-b01a-409a-b888-bfa0f2235398")]
            public virtual RepoItemInfo UserLoginInfo
            {
                get
                {
                    return _userloginInfo;
                }
            }

            /// <summary>
            /// The AdminEmail item.
            /// </summary>
            [RepositoryItem("3dc86b10-8c57-4bd2-a1e3-f2fda9c6f598")]
            public virtual Ranorex.InputTag AdminEmail
            {
                get
                {
                    return _adminemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AdminEmail item info.
            /// </summary>
            [RepositoryItemInfo("3dc86b10-8c57-4bd2-a1e3-f2fda9c6f598")]
            public virtual RepoItemInfo AdminEmailInfo
            {
                get
                {
                    return _adminemailInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("5817c855-6be6-4d08-a337-f278a062e4d0")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("5817c855-6be6-4d08-a337-f278a062e4d0")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The LogInd item.
            /// </summary>
            [RepositoryItem("61d50a52-2471-4470-89f2-39bb33dfbada")]
            public virtual Ranorex.ATag LogInd
            {
                get
                {
                    return _logindInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogInd item info.
            /// </summary>
            [RepositoryItemInfo("61d50a52-2471-4470-89f2-39bb33dfbada")]
            public virtual RepoItemInfo LogIndInfo
            {
                get
                {
                    return _logindInfo;
                }
            }

            /// <summary>
            /// The WpSubmit item.
            /// </summary>
            [RepositoryItem("5a302508-2866-49d1-afc5-bb182774c100")]
            public virtual Ranorex.InputTag WpSubmit
            {
                get
                {
                    return _wpsubmitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The WpSubmit item info.
            /// </summary>
            [RepositoryItemInfo("5a302508-2866-49d1-afc5-bb182774c100")]
            public virtual RepoItemInfo WpSubmitInfo
            {
                get
                {
                    return _wpsubmitInfo;
                }
            }

            /// <summary>
            /// The Content item.
            /// </summary>
            [RepositoryItem("989b25fa-61bd-4568-a444-4929a399dcea")]
            public virtual Ranorex.TextAreaTag Content
            {
                get
                {
                    return _contentInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The Content item info.
            /// </summary>
            [RepositoryItemInfo("989b25fa-61bd-4568-a444-4929a399dcea")]
            public virtual RepoItemInfo ContentInfo
            {
                get
                {
                    return _contentInfo;
                }
            }

            /// <summary>
            /// The SavePost item.
            /// </summary>
            [RepositoryItem("f4b6474c-23b1-4923-88ce-dc420dbb7b2b")]
            public virtual Ranorex.InputTag SavePost
            {
                get
                {
                    return _savepostInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SavePost item info.
            /// </summary>
            [RepositoryItemInfo("f4b6474c-23b1-4923-88ce-dc420dbb7b2b")]
            public virtual RepoItemInfo SavePostInfo
            {
                get
                {
                    return _savepostInfo;
                }
            }

            /// <summary>
            /// The Inside item.
            /// </summary>
            [RepositoryItem("718a3a78-2146-4a6e-91ca-a418aff259df")]
            public virtual Ranorex.DivTag Inside
            {
                get
                {
                    return _insideInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Inside item info.
            /// </summary>
            [RepositoryItemInfo("718a3a78-2146-4a6e-91ca-a418aff259df")]
            public virtual RepoItemInfo InsideInfo
            {
                get
                {
                    return _insideInfo;
                }
            }

            /// <summary>
            /// The DenGodeHistorieOvigsSenesteBogOm item.
            /// </summary>
            [RepositoryItem("0eaa612e-2fef-4cdb-b936-c7cc2d3b61c8")]
            public virtual Ranorex.PTag DenGodeHistorieOvigsSenesteBogOm
            {
                get
                {
                    return _dengodehistorieovigssenestebogomInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The DenGodeHistorieOvigsSenesteBogOm item info.
            /// </summary>
            [RepositoryItemInfo("0eaa612e-2fef-4cdb-b936-c7cc2d3b61c8")]
            public virtual RepoItemInfo DenGodeHistorieOvigsSenesteBogOmInfo
            {
                get
                {
                    return _dengodehistorieovigssenestebogomInfo;
                }
            }

            /// <summary>
            /// The Language item.
            /// </summary>
            [RepositoryItem("7706c093-9c04-4040-8f52-729d988bece9")]
            public virtual Ranorex.SelectTag Language
            {
                get
                {
                    return _languageInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Language item info.
            /// </summary>
            [RepositoryItemInfo("7706c093-9c04-4040-8f52-729d988bece9")]
            public virtual RepoItemInfo LanguageInfo
            {
                get
                {
                    return _languageInfo;
                }
            }

            /// <summary>
            /// The Title item.
            /// </summary>
            [RepositoryItem("cb8306c0-7bf5-4e6a-b8ad-dab2eb3847be")]
            public virtual Ranorex.InputTag Title
            {
                get
                {
                    return _titleInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Title item info.
            /// </summary>
            [RepositoryItemInfo("cb8306c0-7bf5-4e6a-b8ad-dab2eb3847be")]
            public virtual RepoItemInfo TitleInfo
            {
                get
                {
                    return _titleInfo;
                }
            }

            /// <summary>
            /// The TilpasDitWebsted item.
            /// </summary>
            [RepositoryItem("77f0374a-60f7-4b0a-9704-9eadbda64c06")]
            public virtual Ranorex.ATag TilpasDitWebsted
            {
                get
                {
                    return _tilpasditwebstedInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TilpasDitWebsted item info.
            /// </summary>
            [RepositoryItemInfo("77f0374a-60f7-4b0a-9704-9eadbda64c06")]
            public virtual RepoItemInfo TilpasDitWebstedInfo
            {
                get
                {
                    return _tilpasditwebstedInfo;
                }
            }

            /// <summary>
            /// The H3TagFarver item.
            /// </summary>
            [RepositoryItem("188de965-b968-4361-b0e6-fc1a8bc64715")]
            public virtual Ranorex.H3Tag H3TagFarver
            {
                get
                {
                    return _h3tagfarverInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The H3TagFarver item info.
            /// </summary>
            [RepositoryItemInfo("188de965-b968-4361-b0e6-fc1a8bc64715")]
            public virtual RepoItemInfo H3TagFarverInfo
            {
                get
                {
                    return _h3tagfarverInfo;
                }
            }

            /// <summary>
            /// The Custom item.
            /// </summary>
            [RepositoryItem("71d2bbb0-2eeb-452d-88d8-588d07b566fe")]
            public virtual Ranorex.LabelTag Custom
            {
                get
                {
                    return _customInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The Custom item info.
            /// </summary>
            [RepositoryItemInfo("71d2bbb0-2eeb-452d-88d8-588d07b566fe")]
            public virtual RepoItemInfo CustomInfo
            {
                get
                {
                    return _customInfo;
                }
            }

            /// <summary>
            /// The IrisSliderOffsetUiCornerAllUiSlid item.
            /// </summary>
            [RepositoryItem("c3e89168-dca9-4733-8c12-54ef9a01ea1e")]
            public virtual Ranorex.DivTag IrisSliderOffsetUiCornerAllUiSlid
            {
                get
                {
                    return _irisslideroffsetuicorneralluislidInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The IrisSliderOffsetUiCornerAllUiSlid item info.
            /// </summary>
            [RepositoryItemInfo("c3e89168-dca9-4733-8c12-54ef9a01ea1e")]
            public virtual RepoItemInfo IrisSliderOffsetUiCornerAllUiSlidInfo
            {
                get
                {
                    return _irisslideroffsetuicorneralluislidInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("85ea9211-cab2-44eb-a802-0dbb45e6b9af")]
            public virtual Ranorex.InputTag Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("85ea9211-cab2-44eb-a802-0dbb45e6b9af")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The EditPostLayout folder.
            /// </summary>
            [RepositoryFolder("f250d7ac-42cf-44a1-8b9b-8091aa2641d0")]
            public virtual MyTest23RepositoryFolders.EditPostLayoutFolder EditPostLayout
            {
                get { return _editpostlayout; }
            }

            /// <summary>
            /// The Setup folder.
            /// </summary>
            [RepositoryFolder("b8b82088-f673-4c15-a57a-8717d299c5a4")]
            public virtual MyTest23RepositoryFolders.SetupFolder Setup
            {
                get { return _setup; }
            }

            /// <summary>
            /// The FormTableInstallSuccess folder.
            /// </summary>
            [RepositoryFolder("d164e918-5ed5-4496-a092-66d9a8566ef6")]
            public virtual MyTest23RepositoryFolders.FormTableInstallSuccessFolder FormTableInstallSuccess
            {
                get { return _formtableinstallsuccess; }
            }
        }

        /// <summary>
        /// The EditPostLayoutFolder folder.
        /// </summary>
        [RepositoryFolder("f250d7ac-42cf-44a1-8b9b-8091aa2641d0")]
        public partial class EditPostLayoutFolder : RepoGenBaseFolder
        {
            RepoItemInfo _udgivInfo;
            RepoItemInfo _visindlaegInfo;
            RepoItemInfo _blocklibraryclassictoolbarhasadvanInfo;
            RepoItemInfo _blockeditorwritingflowclickredirecInfo;
            RepoItemInfo _udgiv1Info;
            RepoItemInfo _erduklartilatudgiveInfo;
            RepoItemInfo _ojeblikkeligtInfo;
            RepoItemInfo _tdtag10Info;

            /// <summary>
            /// Creates a new EditPostLayout  folder.
            /// </summary>
            public EditPostLayoutFolder(RepoGenBaseFolder parentFolder) :
                    base("EditPostLayout", ".//div[#'editor']/div/div/div", parentFolder, 30000, null, false, "f250d7ac-42cf-44a1-8b9b-8091aa2641d0", "")
            {
                _udgivInfo = new RepoItemInfo(this, "Udgiv", "div[1]/div[2]/div[1]/button[@innertext='Udgiv...']", 30000, null, "0127aafb-2675-403c-b715-7db29de577ef");
                _visindlaegInfo = new RepoItemInfo(this, "VisIndlaeg", "div[2]/div[3]//div[@innertext='Indlæg udgivet.']/a[@innertext='Vis indlæg']", 30000, null, "1f53b2e6-d8e2-49b5-b4bf-ee0ed910d29b");
                _blocklibraryclassictoolbarhasadvanInfo = new RepoItemInfo(this, "BlockLibraryClassicToolbarHasAdvan", "div[2]/div[4]/div/div/div[1]/div/div/div[2]/div[1]/div[3]/div[2]/div[1]", 30000, null, "85414e1a-3b39-4300-8280-774100c0338d");
                _blockeditorwritingflowclickredirecInfo = new RepoItemInfo(this, "BlockEditorWritingFlowClickRedirec", "div[2]/div[4]/div/div/div[2]", 30000, null, "d739081a-a96a-4026-b3e7-357d78995020");
                _udgiv1Info = new RepoItemInfo(this, "Udgiv1", "div[3]/div/div/div[1]/div/div/button[@innertext='Udgiv']", 30000, null, "5f848014-17c0-44d7-82fe-a8f3953f6cbd");
                _erduklartilatudgiveInfo = new RepoItemInfo(this, "ErDuKlarTilAtUdgive", "div[3]/div/div/div[2]/div/div[1]/strong[@innertext='Er du klar til at udgive?']", 30000, null, "27e502e6-de75-4d00-93c4-c263ffa4b7d3");
                _ojeblikkeligtInfo = new RepoItemInfo(this, "Ojeblikkeligt", "div[3]/div/div/div[2]/div/div[3]/?/?/button[@innertext='Udgiv:']/span[@innertext='Øjeblikkeligt']", 30000, null, "4868a310-1eb4-4418-b678-6feee342a880");
                _tdtag10Info = new RepoItemInfo(this, "TdTag10", "div[3]/div/div/div[2]/div/div[3]/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/?/?/table/tbody/tr[2]/td[@innertext='10']", 30000, null, "67b674a2-21fb-44b5-b57d-0e7860d4825a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f250d7ac-42cf-44a1-8b9b-8091aa2641d0")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f250d7ac-42cf-44a1-8b9b-8091aa2641d0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Udgiv item.
            /// </summary>
            [RepositoryItem("0127aafb-2675-403c-b715-7db29de577ef")]
            public virtual Ranorex.ButtonTag Udgiv
            {
                get
                {
                    return _udgivInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Udgiv item info.
            /// </summary>
            [RepositoryItemInfo("0127aafb-2675-403c-b715-7db29de577ef")]
            public virtual RepoItemInfo UdgivInfo
            {
                get
                {
                    return _udgivInfo;
                }
            }

            /// <summary>
            /// The VisIndlaeg item.
            /// </summary>
            [RepositoryItem("1f53b2e6-d8e2-49b5-b4bf-ee0ed910d29b")]
            public virtual Ranorex.ATag VisIndlaeg
            {
                get
                {
                    return _visindlaegInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The VisIndlaeg item info.
            /// </summary>
            [RepositoryItemInfo("1f53b2e6-d8e2-49b5-b4bf-ee0ed910d29b")]
            public virtual RepoItemInfo VisIndlaegInfo
            {
                get
                {
                    return _visindlaegInfo;
                }
            }

            /// <summary>
            /// The BlockLibraryClassicToolbarHasAdvan item.
            /// </summary>
            [RepositoryItem("85414e1a-3b39-4300-8280-774100c0338d")]
            public virtual Ranorex.DivTag BlockLibraryClassicToolbarHasAdvan
            {
                get
                {
                    return _blocklibraryclassictoolbarhasadvanInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BlockLibraryClassicToolbarHasAdvan item info.
            /// </summary>
            [RepositoryItemInfo("85414e1a-3b39-4300-8280-774100c0338d")]
            public virtual RepoItemInfo BlockLibraryClassicToolbarHasAdvanInfo
            {
                get
                {
                    return _blocklibraryclassictoolbarhasadvanInfo;
                }
            }

            /// <summary>
            /// The BlockEditorWritingFlowClickRedirec item.
            /// </summary>
            [RepositoryItem("d739081a-a96a-4026-b3e7-357d78995020")]
            public virtual Ranorex.DivTag BlockEditorWritingFlowClickRedirec
            {
                get
                {
                    return _blockeditorwritingflowclickredirecInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BlockEditorWritingFlowClickRedirec item info.
            /// </summary>
            [RepositoryItemInfo("d739081a-a96a-4026-b3e7-357d78995020")]
            public virtual RepoItemInfo BlockEditorWritingFlowClickRedirecInfo
            {
                get
                {
                    return _blockeditorwritingflowclickredirecInfo;
                }
            }

            /// <summary>
            /// The Udgiv1 item.
            /// </summary>
            [RepositoryItem("5f848014-17c0-44d7-82fe-a8f3953f6cbd")]
            public virtual Ranorex.ButtonTag Udgiv1
            {
                get
                {
                    return _udgiv1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Udgiv1 item info.
            /// </summary>
            [RepositoryItemInfo("5f848014-17c0-44d7-82fe-a8f3953f6cbd")]
            public virtual RepoItemInfo Udgiv1Info
            {
                get
                {
                    return _udgiv1Info;
                }
            }

            /// <summary>
            /// The ErDuKlarTilAtUdgive item.
            /// </summary>
            [RepositoryItem("27e502e6-de75-4d00-93c4-c263ffa4b7d3")]
            public virtual Ranorex.StrongTag ErDuKlarTilAtUdgive
            {
                get
                {
                    return _erduklartilatudgiveInfo.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The ErDuKlarTilAtUdgive item info.
            /// </summary>
            [RepositoryItemInfo("27e502e6-de75-4d00-93c4-c263ffa4b7d3")]
            public virtual RepoItemInfo ErDuKlarTilAtUdgiveInfo
            {
                get
                {
                    return _erduklartilatudgiveInfo;
                }
            }

            /// <summary>
            /// The Ojeblikkeligt item.
            /// </summary>
            [RepositoryItem("4868a310-1eb4-4418-b678-6feee342a880")]
            public virtual Ranorex.SpanTag Ojeblikkeligt
            {
                get
                {
                    return _ojeblikkeligtInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Ojeblikkeligt item info.
            /// </summary>
            [RepositoryItemInfo("4868a310-1eb4-4418-b678-6feee342a880")]
            public virtual RepoItemInfo OjeblikkeligtInfo
            {
                get
                {
                    return _ojeblikkeligtInfo;
                }
            }

            /// <summary>
            /// The TdTag10 item.
            /// </summary>
            [RepositoryItem("67b674a2-21fb-44b5-b57d-0e7860d4825a")]
            public virtual Ranorex.TdTag TdTag10
            {
                get
                {
                    return _tdtag10Info.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The TdTag10 item info.
            /// </summary>
            [RepositoryItemInfo("67b674a2-21fb-44b5-b57d-0e7860d4825a")]
            public virtual RepoItemInfo TdTag10Info
            {
                get
                {
                    return _tdtag10Info;
                }
            }
        }

        /// <summary>
        /// The SetupFolder folder.
        /// </summary>
        [RepositoryFolder("b8b82088-f673-4c15-a57a-8717d299c5a4")]
        public partial class SetupFolder : RepoGenBaseFolder
        {
            RepoItemInfo _stepInfo;
            RepoItemInfo _pwweakInfo;
            RepoItemInfo _adminpasswordInfo;

            /// <summary>
            /// Creates a new Setup  folder.
            /// </summary>
            public SetupFolder(RepoGenBaseFolder parentFolder) :
                    base("Setup", ".//form[#'setup']", parentFolder, 30000, null, false, "b8b82088-f673-4c15-a57a-8717d299c5a4", "")
            {
                _stepInfo = new RepoItemInfo(this, "Step", "p", 30000, null, "c4599117-974c-47a8-a388-6142097b5e54");
                _pwweakInfo = new RepoItemInfo(this, "PwWeak", "table//label[@innertext>'Bekræft brug af svag']/input[@name='pw_weak']", 30000, null, "d1912b61-5a80-41b4-96e9-c145065b91fc");
                _adminpasswordInfo = new RepoItemInfo(this, "AdminPassword", "table/tbody/tr[3]//input[@name='admin_password']", 30000, null, "33f738d6-0871-4a3e-b499-89cfe8f57868");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b8b82088-f673-4c15-a57a-8717d299c5a4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b8b82088-f673-4c15-a57a-8717d299c5a4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Step item.
            /// </summary>
            [RepositoryItem("c4599117-974c-47a8-a388-6142097b5e54")]
            public virtual Ranorex.PTag Step
            {
                get
                {
                    return _stepInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Step item info.
            /// </summary>
            [RepositoryItemInfo("c4599117-974c-47a8-a388-6142097b5e54")]
            public virtual RepoItemInfo StepInfo
            {
                get
                {
                    return _stepInfo;
                }
            }

            /// <summary>
            /// The PwWeak item.
            /// </summary>
            [RepositoryItem("d1912b61-5a80-41b4-96e9-c145065b91fc")]
            public virtual Ranorex.InputTag PwWeak
            {
                get
                {
                    return _pwweakInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PwWeak item info.
            /// </summary>
            [RepositoryItemInfo("d1912b61-5a80-41b4-96e9-c145065b91fc")]
            public virtual RepoItemInfo PwWeakInfo
            {
                get
                {
                    return _pwweakInfo;
                }
            }

            /// <summary>
            /// The AdminPassword item.
            /// </summary>
            [RepositoryItem("33f738d6-0871-4a3e-b499-89cfe8f57868")]
            public virtual Ranorex.InputTag AdminPassword
            {
                get
                {
                    return _adminpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AdminPassword item info.
            /// </summary>
            [RepositoryItemInfo("33f738d6-0871-4a3e-b499-89cfe8f57868")]
            public virtual RepoItemInfo AdminPasswordInfo
            {
                get
                {
                    return _adminpasswordInfo;
                }
            }
        }

        /// <summary>
        /// The FormTableInstallSuccessFolder folder.
        /// </summary>
        [RepositoryFolder("d164e918-5ed5-4496-a092-66d9a8566ef6")]
        public partial class FormTableInstallSuccessFolder : RepoGenBaseFolder
        {
            RepoItemInfo _jmeedomInfo;
            RepoItemInfo _dinvalgteadgangskodeInfo;
            RepoItemInfo _sometdtagInfo;

            /// <summary>
            /// Creates a new FormTableInstallSuccess  folder.
            /// </summary>
            public FormTableInstallSuccessFolder(RepoGenBaseFolder parentFolder) :
                    base("FormTableInstallSuccess", "body/table", parentFolder, 30000, null, false, "d164e918-5ed5-4496-a092-66d9a8566ef6", "")
            {
                _jmeedomInfo = new RepoItemInfo(this, "Jmeedom", ".//td[@innertext='jmeedom']", 30000, null, "9e49fa78-886b-48aa-a8cd-347047923b9c");
                _dinvalgteadgangskodeInfo = new RepoItemInfo(this, "DinValgteAdgangskode", "tbody/tr[2]//em[@innertext='Din valgte adgangskode.']", 30000, null, "a2ccfaf4-bd5e-413c-9b36-bbe330736e6e");
                _sometdtagInfo = new RepoItemInfo(this, "SomeTdTag", "tbody/tr[2]/td", 30000, null, "43cb72e3-c55d-4fed-b50d-567222de2307");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d164e918-5ed5-4496-a092-66d9a8566ef6")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d164e918-5ed5-4496-a092-66d9a8566ef6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Jmeedom item.
            /// </summary>
            [RepositoryItem("9e49fa78-886b-48aa-a8cd-347047923b9c")]
            public virtual Ranorex.TdTag Jmeedom
            {
                get
                {
                    return _jmeedomInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Jmeedom item info.
            /// </summary>
            [RepositoryItemInfo("9e49fa78-886b-48aa-a8cd-347047923b9c")]
            public virtual RepoItemInfo JmeedomInfo
            {
                get
                {
                    return _jmeedomInfo;
                }
            }

            /// <summary>
            /// The DinValgteAdgangskode item.
            /// </summary>
            [RepositoryItem("a2ccfaf4-bd5e-413c-9b36-bbe330736e6e")]
            public virtual Ranorex.EmTag DinValgteAdgangskode
            {
                get
                {
                    return _dinvalgteadgangskodeInfo.CreateAdapter<Ranorex.EmTag>(true);
                }
            }

            /// <summary>
            /// The DinValgteAdgangskode item info.
            /// </summary>
            [RepositoryItemInfo("a2ccfaf4-bd5e-413c-9b36-bbe330736e6e")]
            public virtual RepoItemInfo DinValgteAdgangskodeInfo
            {
                get
                {
                    return _dinvalgteadgangskodeInfo;
                }
            }

            /// <summary>
            /// The SomeTdTag item.
            /// </summary>
            [RepositoryItem("43cb72e3-c55d-4fed-b50d-567222de2307")]
            public virtual Ranorex.TdTag SomeTdTag
            {
                get
                {
                    return _sometdtagInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The SomeTdTag item info.
            /// </summary>
            [RepositoryItemInfo("43cb72e3-c55d-4fed-b50d-567222de2307")]
            public virtual RepoItemInfo SomeTdTagInfo
            {
                get
                {
                    return _sometdtagInfo;
                }
            }
        }

        /// <summary>
        /// The NyFaneGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("f7b1980f-ac83-405a-a951-18633b41c2fb")]
        public partial class NyFaneGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _adresseogsogelinjeInfo;
            RepoItemInfo _adresseogsogelinje1Info;

            /// <summary>
            /// Creates a new NyFaneGoogleChrome  folder.
            /// </summary>
            public NyFaneGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NyFaneGoogleChrome", "/form[@title='Ny fane – Google Chrome']", parentFolder, 30000, null, true, "f7b1980f-ac83-405a-a951-18633b41c2fb", "")
            {
                _adresseogsogelinjeInfo = new RepoItemInfo(this, "AdresseOgSogelinje", "container[@accessiblename='Ny fane – Google Chrome']/container[@accessiblename='Google Chrome']/container[2]/container[1]/container[2]/container[1]/text[@accessiblename='Adresse og søgelinje']", 30000, null, "851e2ccc-f230-4ece-8495-b6d26bb168ae");
                _adresseogsogelinje1Info = new RepoItemInfo(this, "AdresseOgSogelinje1", "container[@accessiblename>'localhost – netværksfejl –']/container[@accessiblename='Google Chrome']/container[2]/container[1]/container[2]/container[1]/text[@accessiblename='Adresse og søgelinje']", 30000, null, "c1d5952a-b435-4cec-a56b-fefff9b515bc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f7b1980f-ac83-405a-a951-18633b41c2fb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f7b1980f-ac83-405a-a951-18633b41c2fb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AdresseOgSogelinje item.
            /// </summary>
            [RepositoryItem("851e2ccc-f230-4ece-8495-b6d26bb168ae")]
            public virtual Ranorex.Text AdresseOgSogelinje
            {
                get
                {
                    return _adresseogsogelinjeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AdresseOgSogelinje item info.
            /// </summary>
            [RepositoryItemInfo("851e2ccc-f230-4ece-8495-b6d26bb168ae")]
            public virtual RepoItemInfo AdresseOgSogelinjeInfo
            {
                get
                {
                    return _adresseogsogelinjeInfo;
                }
            }

            /// <summary>
            /// The AdresseOgSogelinje1 item.
            /// </summary>
            [RepositoryItem("c1d5952a-b435-4cec-a56b-fefff9b515bc")]
            public virtual Ranorex.Text AdresseOgSogelinje1
            {
                get
                {
                    return _adresseogsogelinje1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AdresseOgSogelinje1 item info.
            /// </summary>
            [RepositoryItemInfo("c1d5952a-b435-4cec-a56b-fefff9b515bc")]
            public virtual RepoItemInfo AdresseOgSogelinje1Info
            {
                get
                {
                    return _adresseogsogelinje1Info;
                }
            }
        }

        /// <summary>
        /// The NyFaneAppFolder folder.
        /// </summary>
        [RepositoryFolder("95a81178-cf32-44a5-9b71-6708677d5bb2")]
        public partial class NyFaneAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new NyFane  folder.
            /// </summary>
            public NyFaneAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NyFane", "/dom[@domain='newtab']", parentFolder, 30000, null, false, "95a81178-cf32-44a5-9b71-6708677d5bb2", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("95a81178-cf32-44a5-9b71-6708677d5bb2")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("95a81178-cf32-44a5-9b71-6708677d5bb2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
