///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest23
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("2e1cbd99-2b49-4876-bf73-b870e22563ab", ModuleType.Recording, 1)]
    public partial class Recording2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest23Repository repository.
        /// </summary>
        public static MyTest23Repository repo = MyTest23Repository.Instance;

        static Recording2 instance = new Recording2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPressInstallation.Title' at 72;17.", repo.WordPressInstallation.TitleInfo, new RecordItemIndex(0));
            //repo.WordPressInstallation.Title.Click("72;17");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '' with focus on 'WordPressInstallation.Title'.", repo.WordPressInstallation.TitleInfo, new RecordItemIndex(1));
            //repo.WordPressInstallation.Title.PressKeys("");
            //Delay.Milliseconds(20);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'M{LShiftKey up}yPAge{Tab}Wor' with focus on 'WordPressInstallation.Title'.", repo.WordPressInstallation.TitleInfo, new RecordItemIndex(2));
            //repo.WordPressInstallation.Title.PressKeys("M{LShiftKey up}yPAge{Tab}Wor");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}nderful mountains around the world. S{LShiftKey up}tarting with Mount everest' with focus on 'WordPressInstallation'.", repo.WordPressInstallation.SelfInfo, new RecordItemIndex(3));
            //repo.WordPressInstallation.Self.EnsureVisible();
            //Keyboard.Press("{Back}nderful mountains around the world. S{LShiftKey up}tarting with Mount everest");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPressInstallation.SavePost' at 78;22.", repo.WordPressInstallation.SavePostInfo, new RecordItemIndex(4));
            //repo.WordPressInstallation.SavePost.Click("78;22");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPressInstallation.TilpasDitWebsted' at 139;23.", repo.WordPressInstallation.TilpasDitWebstedInfo, new RecordItemIndex(5));
            //repo.WordPressInstallation.TilpasDitWebsted.Click("139;23");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPressInstallation.H3TagFarver' at 207;43.", repo.WordPressInstallation.H3TagFarverInfo, new RecordItemIndex(6));
            //repo.WordPressInstallation.H3TagFarver.Click("207;43");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPressInstallation.Custom' at 14;20.", repo.WordPressInstallation.CustomInfo, new RecordItemIndex(7));
            //repo.WordPressInstallation.Custom.Click("14;20");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPressInstallation.IrisSliderOffsetUiCornerAllUiSlid' at 134;38.", repo.WordPressInstallation.IrisSliderOffsetUiCornerAllUiSlidInfo, new RecordItemIndex(8));
            //repo.WordPressInstallation.IrisSliderOffsetUiCornerAllUiSlid.Click("134;38");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPressInstallation.Save' at 55;31.", repo.WordPressInstallation.SaveInfo, new RecordItemIndex(9));
            //repo.WordPressInstallation.Save.Click("55;31");
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
